- name: Clone dotfiles
  ansible.builtin.git:
    repo: "https://github.com/geloman-likes-rust/dotfiles"
    dest: "~/.dotfiles"
    clone: true
  become_user: geloman

- name: Symlink .gitconfig
  ansible.builtin.file:
    src: "~/.dotfiles/.gitconfig"
    dest: "~/.gitconfig"
    state: link
  become_user: geloman
