- hosts: localhost
  become: yes
  pre_tasks:
    - name: Update and Upgrade packages
      when: ansible_distribution in ["Debian", "Ubuntu"]
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
  roles:
    - common
    - git
    - zsh
    - neovim
    - terraform
    - docker
    - nodejs
    - golang
    - stylua
