name: Publish docker image to DockerHub

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .github/**

jobs:
  publish:
    name: Publish to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            "geloman/dotfiles:latest"
            "geloman/dotfiles:${GITHUB_SHA:0:7}"
